source 'https://github.com/CocoaPods/Specs.git'
target 'caradviseui' do
  pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'Core',
    'RCTImage',
    'RCTNetwork',
    'RCTText',
    'RCTWebSocket'
  ]
  pod 'react-native-braintree', :path => '../node_modules/react-native-braintree'
  pod 'CodePush', :path => '../node_modules/react-native-code-push'
  pod 'Branch'
  pod 'OneSignal'
end
